name: FirstZucov

on: 
    push:
        branches:
        - main
        - dev
    pull_request:
        branches:
        - main
        - dev

env:
    DTN_VER : '9.0.x'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Get Code From Repos
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{env.DTN_VER}}
            
            - name: Restorre Dependencies
              run: dotnet restore
    
    test:
        runs-on: ubuntu-lates
        needs: build

        steps:
            - name: Build Solution
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --no-build --configuration Release --verbosity normal